version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/s2gp
    ports:
      - 3000:3000
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    depends_on:
      - db
    stdin_open: true
    tty: true
  webpack:
    build: .
    command: bash -c "./bin/webpack-dev-server"
    volumes:
      - .:/s2gp
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - 1025:1025 
      - 1080:1080
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ./tmp/minio/data:/data
    ports:
      - 9000:9000 
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
